const classicalCard=document.createElement('section');classicalCard.className='card classical-card';
classicalCard.innerHTML='<p class="pill">REPERTORIO CLÁSICO</p><h2>Tu pieza, paso a paso</h2><label for="classicalSelect">Elige una pieza según tu control actual</label><select id="classicalSelect"></select><p id="classicalLevel" class="score-type"></p><p id="classicalFocus"></p><button type="button" id="classicalScore">Ver partitura clásica</button><a id="classicalSource" target="_blank" rel="noopener">Fuente y descarga ↗</a><label class="file-label" for="classicalUpload">Cargar PDF de esta pieza</label><input id="classicalUpload" type="file" accept="application/pdf,.pdf"><p id="classicalFileStatus" role="status"></p>';
sidebar.prepend(classicalCard);
const classicalPicker=document.getElementById('classicalSelect');
classicalPieces.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;classicalPicker.append(o);});
let classicBlobURL=null;
const minuetPDF='https://imslp.eu/files/imglnks/euimg/4/43/IMSLP1012732-PMLP357193-treharne_bach_for_early_grades_b.1-7.pdf';
function showClassic(){classicalPicker.value=activeClassic.id;document.getElementById('classicalLevel').textContent=activeClassic.level;document.getElementById('classicalFocus').textContent=activeClassic.focus;document.getElementById('classicalSource').href=activeClassic.score==='bartok'?'https://imslp.org/wiki/Mikrokosmos_for_Piano,_Sz.107_(Bart%C3%B3k,_B%C3%A9la)':'https://imslp.org/wiki/Minuet_in_G_major,_BWV_Anh.114_(Pezold,_Christian)';document.getElementById('classicalFileStatus').textContent='';document.getElementById('attemptForm').reset();document.getElementById('attemptStatus').textContent='';const previous=(Array.isArray(state.classicalAttempts)?state.classicalAttempts:[]).filter(r=>r.piece===activeClassic.id).pop();if(previous){document.getElementById('attemptFragment').value=previous.fragment;document.getElementById('attemptTempo').value=previous.tempo;}showAttemptHistory();}
classicalPicker.addEventListener('change',()=>{activeClassic=classicalPieces.find(p=>p.id===classicalPicker.value);state.classicalPiece=activeClassic.id;showClassic();renderSessions();save();});
document.getElementById('classicalScore').addEventListener('click',async()=>{if(classicBlobURL)URL.revokeObjectURL(classicBlobURL);let record;try{record=await readScore(activeClassic.score);}catch(e){}const url=record?(classicBlobURL=URL.createObjectURL(record.file)):(activeClassic.score==='bartok'?bartokPDF:minuetPDF);openScore(url,activeClassic.name,activeClassic.score==='bartok'?'Volumen I · localiza el número de la pieza en la página.':'Edición Treharne, 1939 · dos pentagramas · 3/4');});
document.getElementById('classicalUpload').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;const id=activeClassic.score;const status=document.getElementById('classicalFileStatus');if(file.size>30*1024*1024||new TextDecoder().decode(await file.slice(0,5).arrayBuffer())!=='%PDF-'){status.textContent='Elige un PDF de hasta 30 MB.';return;}try{await storeScore(id,file);status.textContent='PDF guardado en este navegador: '+file.name;}catch(e){status.textContent='No se pudo guardar el PDF.';}event.target.value='';});
const advance=document.createElement('section');advance.className='card advance-card';advance.innerHTML='<p class="pill">MI AVANCE EN CLÁSICA</p><h2>Más control, luego más tempo</h2><p>Registra una ejecución del mismo fragmento. Una lectura nueva se mide aparte, en la sesión. Este registro es tu autoevaluación.</p><form id="attemptForm"><div class="fields"><label>Fragmento (p. ej. nº 1, compases 1–4)<input id="attemptFragment" required maxlength="100" placeholder="Pieza y compases"></label><label>Tempo · negra por minuto<input id="attemptTempo" type="number" min="20" max="240" required></label><label>Errores de notas<input id="attemptNotes" type="number" min="0" max="999" required></label><label>Errores de duración<input id="attemptRhythm" type="number" min="0" max="999" required></label><label>Paradas<input id="attemptStops" type="number" min="0" max="999" required></label></div><label class="pulse-check"><input id="attemptPulse" type="checkbox"> Mantuve el pulso y toqué con manos sueltas</label><button type="submit">Guardar intento</button><p id="attemptStatus" role="status"></p></form><p id="advanceAdvice" class="goal"></p><div id="attemptHistory"></div><small>Regla docente orientativa: tres intentos limpios del mismo fragmento y tempo, en al menos dos días, antes de probar +4 bpm. Si pierdes control, vuelve al tempo anterior. También avanzas al leer mejor, equilibrar voces y tocar frases completas.</small>';
practice.appendChild(advance);
document.getElementById('attemptForm').addEventListener('submit',event=>{event.preventDefault();const fragment=document.getElementById('attemptFragment').value.trim();if(!fragment)return;const record={id:Date.now(),piece:activeClassic.id,date:new Date().toISOString(),day:new Date().toLocaleDateString('sv-SE'),fragment,tempo:Number(document.getElementById('attemptTempo').value),notes:Number(document.getElementById('attemptNotes').value),rhythm:Number(document.getElementById('attemptRhythm').value),stops:Number(document.getElementById('attemptStops').value),pulse:document.getElementById('attemptPulse').checked};if(!Array.isArray(state.classicalAttempts))state.classicalAttempts=[];state.classicalAttempts.push(record);save();document.getElementById('attemptStatus').textContent=storageOK?'Intento guardado.':'No se pudo conservar el intento. Descarga tu registro.';document.getElementById('attemptPulse').checked=false;document.getElementById('attemptForm').reset();document.getElementById('attemptStatus').textContent='';const previous=(Array.isArray(state.classicalAttempts)?state.classicalAttempts:[]).filter(r=>r.piece===activeClassic.id).pop();if(previous){document.getElementById('attemptFragment').value=previous.fragment;document.getElementById('attemptTempo').value=previous.tempo;}showAttemptHistory();});
function showAttemptHistory(){const all=Array.isArray(state.classicalAttempts)?state.classicalAttempts:[];const records=all.filter(r=>r.piece===activeClassic.id);const area=document.getElementById('attemptHistory');area.replaceChildren();const advice=document.getElementById('advanceAdvice');if(!records.length){advice.textContent='Primer objetivo: registra 2–4 compases a un tempo cómodo. Conserva ese fragmento y tempo para comparar.';return;}const last=records[records.length-1];const comparable=records.filter(r=>r.fragment.trim().toLowerCase()===last.fragment.trim().toLowerCase()&&r.tempo===last.tempo);let clean=[];for(let i=comparable.length-1;i>=0;i--){const r=comparable[i];if(r.notes||r.rhythm||r.stops||!r.pulse)break;clean.push(r);}const ready=clean.length>=3&&new Set(clean.map(r=>r.day)).size>=2;advice.textContent=ready?'Tres intentos limpios en al menos dos días. Puedes probar '+(last.tempo+4)+' bpm en este fragmento; confirma que conservas el control.':'Mantén '+last.tempo+' bpm en «'+last.fragment+'». Último intento: '+last.notes+' errores de notas, '+last.rhythm+' de duración y '+last.stops+' paradas. Prioriza el punto que interrumpe el pulso.';const table=document.createElement('table');table.innerHTML='<caption>Últimos intentos · '+activeClassic.name+'</caption><thead><tr><th>Fecha / fragmento</th><th>Bpm</th><th>Notas / ritmo / paradas</th><th>Pulso</th></tr></thead>';const body=document.createElement('tbody');records.slice(-6).reverse().forEach(r=>{const row=document.createElement('tr');[new Date(r.date).toLocaleDateString('es-CL')+' · '+r.fragment,String(r.tempo),r.notes+' / '+r.rhythm+' / '+r.stops,r.pulse?'Estable':'Por trabajar'].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell);});body.append(row);});table.append(body);area.append(table);}
showClassic();
