const scoreCatalog={
fidelidad:{type:'Piano y voz · PDF descargable',note:'Edición publicada por Partituras Cristianas, 7 páginas. Descarga el archivo y usa «Cargar mi PDF» para verlo aquí. No es un arreglo inicial: empieza por una frase de la melodía y un bajo sencillo.',download:'https://www.partiturascristianas.com/component/phocadownload/category/4-marcos-witt?download=41:tu-fidelidad',source:'https://www.partiturascristianas.com/tu-fidelidad'},
gracias:{type:'Piano y voz · PDF descargable',note:'Edición publicada por Partituras Cristianas, 4 páginas, con acompañamiento escrito. Descárgala y cárgala en el visor. Simplifica los patrones rápidos antes de juntar las manos.',download:'https://www.partiturascristianas.com/component/phocadownload/category/4-marcos-witt?download=36:gracias',source:'https://www.partiturascristianas.com/gracias'},
'mi-vida':{type:'Piano y voz · versión inglesa',note:'All I Have Is Christ: partitura oficial de Sovereign Grace, 4 páginas, re mayor y 3/4. Corresponde a la canción original de Mi vida es Cristo, con letra inglesa y arreglo propio. El cifrado español disponible está en otra tonalidad; no combines ambas versiones sin transponer.',pdf:'https://sovereigngracemusic.s3.amazonaws.com/wp-content/uploads/20240208130522/All-I-Have-Is-Christ-WG22_PIANO-LEAD_D_BE_081423-BK-PIANO-VOCAL.pdf',chart:'https://sovereigngracemusic.s3.amazonaws.com/wp-content/uploads/20230821180711/mi_vida_es_cristo-EDQA-guitarra.pdf',source:'https://sovereigngracemusic.com/music/songs/all-i-have-is-christ/'},
'dios-adoramos':{type:'Cifrado de acordes · sin pentagramas',note:'Hoja oficial de acordes en fa sostenido, publicada por Sovereign Grace. Sirve para acompañar; no contiene las notas de ambas manos. Usa el bajo y los acordes del plan para llevarla al piano.',pdf:'https://sovereigngracemusic.s3.amazonaws.com/wp-content/uploads/20230821180712/el_dios_que_adoramos-guitarra.pdf',source:'https://sovereigngracemusic.com/music/songs/el-dios-que-adoramos/'},
hermoso:{type:'Piano y voz · edición comercial',note:'La partitura de piano y voz en español está disponible en PraiseCharts y en el cancionero oficial Hay Más de Hillsong. El PDF completo requiere adquisición. Si ya lo tienes, cárgalo aquí para estudiar.',source:'https://hillsongresources.com/products/hay-mas-sheet-music',purchase:'https://www.praisecharts.com/songs/details/73720/hermoso-nombre-what-a-beautiful-name'},
aqui:{type:'Recursos de canción · PDF personal',note:'El recurso de Worship Together contiene información y cifrado de la canción. No se ha verificado un PDF gratuito de piano completo para integrar. Puedes cargar una partitura que ya tengas.',source:'https://www.worshiptogether.com/es/canciones/aqui-estoy-united/'}
};
const bartokPDF='https://imslp.eu/files/imglnks/euimg/a/a9/IMSLP907523-PMLP3661-Bartok_-_Mikrokosmos_I.pdf';
const scores=document.createElement('section');scores.className='card scores-card';scores.innerHTML='<p class="pill">PARTITURAS</p><h2>La música, a la vista</h2><p id="scoreType" class="score-type"></p><p id="scoreNote"></p><div class="score-actions"><button type="button" id="viewScore">Ver partitura</button><a id="scoreDownload" target="_blank" rel="noopener">Descargar PDF ↗</a><a id="scoreSource" target="_blank" rel="noopener">Ver fuente ↗</a></div><label class="file-label" for="personalScore">Cargar mi PDF</label><input id="personalScore" type="file" accept="application/pdf,.pdf"><p id="scoreStatus" role="status"></p><button class="secondary" type="button" id="viewBartok">Abrir Mikrokosmos I</button><small>Los PDFs que cargas se guardan en este navegador. No se envían a un servidor.</small>';
sidebar.insertBefore(scores,overview);const bundle=document.createElement('input');bundle.type='file';bundle.multiple=true;bundle.accept='application/pdf,.pdf';bundle.id='scoreBundle';bundle.hidden=true;const bundleButton=document.createElement('button');bundleButton.type='button';bundleButton.className='secondary';bundleButton.textContent='Cargar colección de PDFs';bundleButton.addEventListener('click',()=>bundle.click());scores.append(bundleButton,bundle);
const scoreDialog=document.createElement('dialog');scoreDialog.className='score-dialog';scoreDialog.innerHTML='<header><div><strong id="viewerTitle"></strong><small id="viewerNote"></small></div><button type="button" id="closeScore" aria-label="Cerrar partitura">Cerrar ×</button></header><div class="viewer-tools"><a id="viewerOpen" target="_blank" rel="noopener">Abrir PDF en otra pestaña ↗</a><button type="button" class="secondary" id="switchChart" hidden>Ver cifrado español</button></div><div class="page-navigation"><button type="button" id="prevPage" class="secondary">← Anterior</button><span id="pageNumber" role="status"></span><button type="button" id="nextPage" class="secondary">Siguiente →</button><button type="button" id="zoomOut" class="secondary" aria-label="Alejar">−</button><button type="button" id="zoomIn" class="secondary" aria-label="Acercar">+</button></div><div id="scorePages" role="region" aria-label="Página de partitura"></div><p>Si el visor no aparece en tu dispositivo, usa «Abrir PDF en otra pestaña».</p>';
document.body.appendChild(scoreDialog);
const scoreFile=document.getElementById('personalScore');let currentLocal=null,localURL=null,loadVersion=0;
let dbPromise;
function scoreDB(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('piano_private_scores_v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('scores',{keyPath:'song'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return dbPromise;}
async function readScore(id){const db=await scoreDB();return new Promise((resolve,reject)=>{const r=db.transaction('scores','readonly').objectStore('scores').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function storeScore(id,file){const db=await scoreDB();return new Promise((resolve,reject)=>{const tx=db.transaction('scores','readwrite');tx.objectStore('scores').put({song:id,file,name:file.name});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function releaseLocal(){if(localURL)URL.revokeObjectURL(localURL);localURL=null;currentLocal=null;}
function localRecord(record){releaseLocal();currentLocal=record;localURL=URL.createObjectURL(record.file);document.getElementById('scoreStatus').textContent='Tu PDF: '+record.name;document.getElementById('viewScore').disabled=false;document.getElementById('viewScore').textContent='Ver mi PDF';}
async function refreshScores(){const version=++loadVersion;const songId=activeSong.id;const s=scoreCatalog[songId];releaseLocal();document.getElementById('scoreType').textContent=s.type;document.getElementById('scoreNote').textContent=s.note;const open=document.getElementById('viewScore');open.disabled=!s.pdf;open.textContent=s.pdf?'Ver '+(songId==='dios-adoramos'?'acordes':'partitura'):'Carga el PDF para verlo';const dl=document.getElementById('scoreDownload');dl.hidden=!(s.download||s.pdf);dl.href=s.download||s.pdf||'#';const src=document.getElementById('scoreSource');src.href=s.purchase||s.source;src.textContent=s.purchase?'Ver edición de piano ↗':'Ver fuente ↗';document.getElementById('scoreStatus').textContent='';scoreFile.value='';try{const record=await readScore(songId);if(version===loadVersion&&record)localRecord(record);}catch(e){if(version===loadVersion)document.getElementById('scoreStatus').textContent='Puedes abrir un PDF, pero este navegador no permite conservarlo.';}}
function openScore(url,title,note,chart=false){document.getElementById('viewerTitle').textContent=title;document.getElementById('viewerNote').textContent=note;document.getElementById('viewerOpen').href=url;loadCanvas(url);document.getElementById('switchChart').hidden=!chart;scoreDialog.showModal();}
document.getElementById('viewScore').addEventListener('click',()=>{const s=scoreCatalog[activeSong.id];if(localURL)openScore(localURL,activeSong.name,currentLocal.name,!!s.chart);else if(s.pdf)openScore(s.pdf,activeSong.name,s.type,!!s.chart);});
document.getElementById('viewBartok').addEventListener('click',async()=>{let url=bartokPDF;try{const record=await readScore('bartok');if(record)url=URL.createObjectURL(record.file);}catch(e){}openScore(url,'Mikrokosmos · Béla Bartók · Volumen I','Piezas 1–36 · empieza por nº 1–6. Fuente: IMSLP.');});
document.getElementById('switchChart').addEventListener('click',()=>{const s=scoreCatalog[activeSong.id];if(s.chart){loadChart(s.chart);document.getElementById('viewerOpen').href=s.chart;document.getElementById('viewerNote').textContent='Cifrado oficial en do · letra inglesa · sin pentagramas';document.getElementById('switchChart').hidden=true;}});
function closeScore(){scoreDialog.close();clearCanvas();}
document.getElementById('closeScore').addEventListener('click',closeScore);scoreDialog.addEventListener('cancel',()=>clearCanvas());
scoreFile.addEventListener('change',async()=>{const file=scoreFile.files[0];if(!file)return;const id=activeSong.id;const version=loadVersion;const status=document.getElementById('scoreStatus');if(file.size>30*1024*1024){status.textContent='Elige un PDF de hasta 30 MB.';return;}const header=new TextDecoder().decode(await file.slice(0,5).arrayBuffer());if(header!=='%PDF-'){status.textContent='Ese archivo no parece un PDF válido.';return;}if(version!==loadVersion)return;localRecord({file,name:file.name});try{await storeScore(id,file);if(version===loadVersion)status.textContent='Guardado en este navegador: '+file.name;}catch(e){if(version===loadVersion)status.textContent='PDF abierto para esta visita; no se pudo conservar. Vuelve a cargarlo la próxima vez.';}});
picker.addEventListener('change',()=>{if(scoreDialog.open)closeScore();refreshScores();});refreshScores();
let pdfLibrary,pdfDocument,loadingPDF,pageIndex=1,pageZoom=1,documentVersion=0,renderVersion=0,renderTask;
async function pdfLib(){if(!pdfLibrary){pdfLibrary=await import('./vendor/pdf.js');pdfLibrary.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.js';}return pdfLibrary;}
function clearCanvas(){documentVersion++;renderVersion++;if(renderTask)renderTask.cancel();document.getElementById('scorePages').replaceChildren();if(loadingPDF){loadingPDF.destroy().catch(()=>{});loadingPDF=null;}pdfDocument=null;}
async function loadCanvas(url){clearCanvas();const version=documentVersion;pageIndex=1;pageZoom=1;const region=document.getElementById('scorePages');region.textContent='Cargando partitura…';document.getElementById('pageNumber').textContent='';try{const lib=await pdfLib();const task=lib.getDocument({url,isEvalSupported:false});loadingPDF=task;const doc=await task.promise;if(version!==documentVersion){task.destroy().catch(()=>{});return;}pdfDocument=doc;await renderPage();}catch(e){if(version===documentVersion){region.textContent='No se pudo abrir el PDF desde su sitio. Descárgalo con el enlace superior y usa «Cargar mi PDF» para verlo dentro de la app.';}}}
async function renderPage(){if(!pdfDocument)return;const version=++renderVersion;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch(e){}}const region=document.getElementById('scorePages');const page=await pdfDocument.getPage(pageIndex);if(version!==renderVersion)return;const base=page.getViewport({scale:1});const width=Math.max(280,region.clientWidth-28);const viewport=page.getViewport({scale:width/base.width*pageZoom});const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Partitura, página '+pageIndex);const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';region.replaceChildren(canvas);document.getElementById('pageNumber').textContent=pageIndex+' / '+pdfDocument.numPages;document.getElementById('prevPage').disabled=pageIndex<=1;document.getElementById('nextPage').disabled=pageIndex>=pdfDocument.numPages;renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null});try{await renderTask.promise;}catch(e){if(e.name!=='RenderingCancelledException')region.textContent='No se pudo dibujar esta página. Prueba abrir el PDF en otra pestaña.';}}
document.getElementById('prevPage').addEventListener('click',()=>{if(pdfDocument&&pageIndex>1){pageIndex--;renderPage();}});document.getElementById('nextPage').addEventListener('click',()=>{if(pdfDocument&&pageIndex<pdfDocument.numPages){pageIndex++;renderPage();}});document.getElementById('zoomIn').addEventListener('click',()=>{pageZoom=Math.min(2.5,pageZoom+.25);renderPage();});document.getElementById('zoomOut').addEventListener('click',()=>{pageZoom=Math.max(.5,pageZoom-.25);renderPage();});
async function loadChart(url){try{const record=await readScore('mi-vida-chart');if(record){const blobURL=URL.createObjectURL(record.file);document.getElementById('viewerOpen').href=blobURL;loadCanvas(blobURL);return;}}catch(e){}loadCanvas(url);}
const bundleNames={'tu-fidelidad.pdf':'fidelidad','gracias.pdf':'gracias','mi-vida-es-cristo-piano.pdf':'mi-vida','mi-vida-es-cristo-acordes.pdf':'mi-vida-chart','el-dios-que-adoramos-acordes.pdf':'dios-adoramos','mikrokosmos-1.pdf':'bartok'};
bundle.addEventListener('change',async()=>{let count=0;for(const file of bundle.files){const id=bundleNames[file.name.toLowerCase()];if(!id||file.size>30*1024*1024)continue;const magic=new TextDecoder().decode(await file.slice(0,5).arrayBuffer());if(magic!=='%PDF-')continue;try{await storeScore(id,file);count++;}catch(e){document.getElementById('scoreStatus').textContent='No se pudo guardar la colección en este navegador.';return;}}await refreshScores();document.getElementById('scoreStatus').textContent=count+' PDFs guardados en este navegador.';bundle.value='';});
