const main=document.querySelector('main');
const back=main.querySelector('a');
const topbar=document.createElement('header');topbar.className='topbar';
topbar.innerHTML='<div class="brand"><span class="brand-icon" aria-hidden="true">♬</span> piano<span style="font-weight:400;color:#718171"> / clásica + worship</span></div><small>Un paso a la vez</small>';
topbar.appendChild(back);main.prepend(topbar);
const hero=document.createElement('section');hero.className='hero';
const heroCopy=document.createElement('div');heroCopy.className='hero-copy';
for(const el of [main.querySelector('.pill'),main.querySelector('h1'),main.querySelector('.intro')])heroCopy.appendChild(el);
hero.appendChild(heroCopy);const art=document.createElement('div');art.className='piano-art';art.setAttribute('aria-hidden','true');art.innerHTML='<span>LEER · TOCAR · CRECER</span><div class="keys"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b></b><b></b><b></b><b></b><b></b></div>';hero.appendChild(art);topbar.after(hero);
const workspace=document.createElement('div');workspace.className='workspace';const practice=document.createElement('section');practice.className='practice-column';practice.setAttribute('aria-label','Sesión de práctica');const sidebar=document.createElement('aside');sidebar.className='sidebar';sidebar.setAttribute('aria-label','Canción y herramientas');workspace.append(practice,sidebar);hero.after(workspace);
const song=document.getElementById('worship');sidebar.appendChild(song);
const songGuide=document.createElement('details');songGuide.className='song-guide';const sgSummary=document.createElement('summary');sgSummary.textContent='Cómo trabajar esta canción';songGuide.appendChild(sgSummary);for(const p of Array.from(song.children).filter(x=>x.tagName==='P'&&!x.id&&!x.classList.contains('pill')&&!x.querySelector('a')))songGuide.appendChild(p);song.appendChild(songGuide);sgSummary.after(document.getElementById("songTip"));
const overview=Array.from(main.children).find(x=>x.classList.contains('card'));overview.classList.add('week-summary');overview.querySelector('strong').textContent='Tu semana · 6 sesiones';const library=document.createElement('section');library.className='library';library.innerHTML='<h2>Tu biblioteca de práctica</h2><p>Consulta las guías cuando las necesites.</p>';const routine=document.createElement('details');routine.innerHTML='<summary>Rutina completa y días con poco tiempo</summary>';for(const p of Array.from(overview.querySelectorAll('p:not([id])')))routine.appendChild(p);library.appendChild(routine);sidebar.appendChild(overview);
const timer=document.createElement('div');timer.className='card timer';timer.innerHTML='<p class="timer-label">TIEMPO PARA TOCAR</p><div class="clock" id="clock" role="timer" aria-label="Tiempo restante">35:00</div><div class="timer-actions"><button type="button" id="timerToggle">Comenzar</button><button type="button" id="timerReset">Reiniciar</button></div><small id="timerNote">35 minutos · puedes pausar cuando lo necesites.</small>';sidebar.appendChild(timer);
const nav=document.createElement('nav');nav.className='session-nav';nav.setAttribute('aria-label','Elegir sesión');practice.appendChild(nav);practice.appendChild(root);
let selected=Number.isInteger(state.activeSession)&&state.activeSession>=0&&state.activeSession<6?state.activeSession:0;
const navButtons=[];for(let i=0;i<6;i++){const b=document.createElement('button');b.type='button';b.innerHTML='Sesión<strong>'+(i+1)+'</strong>';b.addEventListener('click',()=>{selected=i;state.activeSession=i;refreshSession();save();});navButtons.push(b);nav.appendChild(b);}
const next=document.createElement('div');next.className='next-session';const nextLabel=document.createElement('small');const nextButton=document.createElement('button');nextButton.type='button';nextButton.textContent='Siguiente sesión →';nextButton.addEventListener('click',()=>{selected=Math.min(5,selected+1);state.activeSession=selected;refreshSession();save();root.scrollIntoView({behavior:'smooth',block:'start'});});next.append(nextLabel,nextButton);practice.appendChild(next);
function refreshSession(){Array.from(root.children).forEach((card,i)=>{card.classList.add('session-card');card.classList.toggle('visible',i===selected);});navButtons.forEach((b,i)=>{b.setAttribute('aria-pressed',String(i===selected));const count=practiceCheckKeys(i).filter(key=>state[key]).length;b.classList.toggle('done',count===6);b.setAttribute('aria-label','Sesión '+(i+1)+', '+count+' de 6 pasos completados');});nextLabel.textContent='Sesión '+(selected+1)+' de 6 · a tu ritmo';nextButton.hidden=selected===5;}
window.refreshSession=refreshSession;root.addEventListener('change',refreshSession);refreshSession();
for(const d of Array.from(main.children).filter(x=>x.tagName==='DETAILS')){d.open=false;library.appendChild(d);}const rest=Array.from(main.children).find(x=>x.classList.contains('card'));if(rest){rest.classList.add('rest-card');library.appendChild(rest);}workspace.after(library);
const warmup=Array.from(library.querySelectorAll('details')).find(d=>d.querySelector('summary').textContent.startsWith('Calentamiento'));warmup.id='guia-calentamiento';const warmLink=document.createElement('a');warmLink.href='#guia-calentamiento';warmLink.textContent='Ver calentamiento paso a paso →';warmLink.className='warm-link';warmLink.addEventListener('click',()=>{warmup.open=true;});nav.before(warmLink);
const exportRow=document.createElement('div');exportRow.className='export-row';const note=Array.from(main.children).find(x=>x.tagName==='P'&&x.querySelector('small'));if(note){note.className='footer-note';exportRow.appendChild(note);}exportRow.appendChild(document.getElementById('export'));main.appendChild(exportRow);
let seconds=35*60,running=false,startedAt=0,startingSeconds=seconds;let ticker;
const toggle=document.getElementById('timerToggle');const clock=document.getElementById('clock');
function displayTime(){clock.textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
function pauseTimer(){running=false;clearInterval(ticker);toggle.textContent=seconds===0?'Volver a comenzar':'Continuar';}
toggle.addEventListener('click',()=>{if(running){seconds=Math.max(0,startingSeconds-Math.floor((Date.now()-startedAt)/1000));pauseTimer();displayTime();return;}if(seconds===0)seconds=35*60;running=true;startedAt=Date.now();startingSeconds=seconds;toggle.textContent='Pausar';ticker=setInterval(()=>{seconds=Math.max(0,startingSeconds-Math.floor((Date.now()-startedAt)/1000));displayTime();if(seconds===0){pauseTimer();document.getElementById('timerNote').textContent='Tiempo cumplido. Registra cómo te fue.';}},250);});
document.getElementById('timerReset').addEventListener('click',()=>{pauseTimer();seconds=35*60;displayTime();toggle.textContent='Comenzar';document.getElementById('timerNote').textContent='35 minutos · puedes pausar cuando lo necesites.';});
